coding a neuron- in a fully connected network every neuron has a connection to every other neurons- let us consider 3 neurons

inputs can depict different type of inputs eg, op from temp sensor, humidity sensor etc


In [2]:
inputs=[1,2,3,2.5]#output from previous layer
weights=[.2,.8,-.5,1.0]#every input have wts
bias=2#unique val for a layer
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias
output


4.8

each neuron with corresponding weightsets, input and bias

In [3]:
inputs=[1,2,3,2.5]#output from previous layer

weights1=[.2,.8,-.5,1.0]#every input have wts
weights2=[.5,-.91,.25,-.5]
weights3=[-.26,-.27,.17,.87]
bias1=2#unique val for a layer
bias2=3
bias3=.5
output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
output


[4.8, 1.18, 2.385]

put it in a loop

In [4]:
inputs=[1,2,3,2.5]
weights=[[.2,.8,-.5,1.0],[.5,-.91,.25,-.5],[-.26,-.27,.17,.87]]
biases=[2,3,.5]
layer_outputs=[]
for nw,nb in zip(weights,biases):
  neuron_output=0
  for ip,wt in zip(inputs,nw):
    neuron_output+=ip*wt#sum of w*x's
  neuron_output+=nb#complete sigma(w*x+b)
  layer_outputs.append(neuron_output)
print(layer_outputs)






[4.8, 1.18, 2.385]


Understanding shapes


vectors, scalars, tensors

1D

eg:[1,2,3,4]

shape=(4,)

type:vector

2D

eg:[[1,2,3,4],[5,6,7,8]]

shape:(2,4)

type:matrix

3D

eg:[[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]

shape:(2,2,4)

type:3d array

dot poduct- element wise multiplication of values in this 

dot product of 2 vectors gives a single scalar value

In [5]:
import numpy as np
inputs=[1,2,3,2.5]#vector
weights=[.2,.8,-.5,1.0]#matrix
bias=2#vector
output=np.dot(inputs,weights)+bias
output

4.8

DOT PRODUCT- layer

In [6]:
inputs=[1,2,3,2.5]#(4,1)
weights=[[.2,.8,-.5,1.0],[.5,-.91,.25,-.5],[-.26,-.27,.17,.87]]#(3,4)
biases=[2,3,.5]#(3,1)
output=np.dot(weights,inputs)+biases#(3,4)*(4,1)=(3,1)+(3,1)=(3,1)
output

array([4.8  , 1.18 , 2.385])

WHY BATCHES?

1. We can compute in parallel

2. it helps with generalization

when we take batches, we are going to consider batch of samples at different intances

batch size- generally- 32,64,128 etc

In [7]:
inputs=[[1,2,3,2.5],[2.0,5.0,-1.0,2.0],[-1.5,2.7,3.3,-.8]]#(3,4)
weights=[[.2,.8,-.5,1.0],[.5,-.91,.25,-.5],[-.26,-.27,.17,.87]]#(3,4)
biases=[2,3,.5]#(3,1)
#(3,4)*(3,4) not be done
#this can be done if (3,4),(4,3) therefore take transpose of wts
output=np.dot(inputs,np.array(weights).T)+biases
output

array([[ 4.8  ,  1.18 ,  2.385],
       [ 8.9  , -1.8  ,  0.2  ],
       [ 1.41 ,  1.018,  0.026]])

ADD LAYERS



In [8]:
inputs=[[1,2,3,2.5],[2.0,5.0,-1.0,2.0],[-1.5,2.7,3.3,-.8]]#(3,4)
weights=[[.2,.8,-.5,1.0],[.5,-.91,.25,-.5],[-.26,-.27,.17,.87]]#(3,4)
biases=[2,3,.5]#(3,1)
weights2=[[.1,-.14,.5],[-.5,.12,-.33],[-.44,.73,-.13]]#(3,4)
biases2=[-1,2,-.5]#(3,1)
#(3,4)*(3,4) not be done
#this can be done if (3,4),(4,3) therefore take transpose of wts
layer1_op=np.dot(inputs,np.array(weights).T)+biases
layer2_op=np.dot(layer1_op,np.array(weights2).T)+biases2
layer2_op

array([[ 0.5073 , -1.04545, -2.06065],
       [ 0.242  , -2.732  , -5.756  ],
       [-0.98852,  1.40858, -0.38064]])

ORGANIZE THE ABOVE CODE- AS OBJECTS

when you save and load a model, you are actually loading the trained weights and the biases

when we initialize wts we choose values btwn -1 and 1 , but smaller the wts better it perform

biases we tend to initialize them as 0(on the graph bias is the intercept)

In [9]:
np.random.seed(0)
X=[[1,2,3,2.5],[2.0,5.0,-1.0,2.0],[-1.5,2.7,3.3,-.8]]#(3,4)->input
class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights=.1*np.random.randn(n_inputs,n_neurons)#randn is just a gaussian distribution around 0, if values are more than  1 multiply by .1
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases
    
layer1=Layer_Dense(len(X[0]),5)
layer2=Layer_Dense(5,2)
layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)





[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


ACTIVATION FUNCTION

1. step fn
2. sigmoid fn(issue- vanishing gradient)
3. relu fn
4. linear activation


In [10]:
np.random.seed(0)
X=[[1,2,3,2.5],[2.0,5.0,-1.0,2.0],[-1.5,2.7,3.3,-.8]]#(3,4)->input
inputs=[0,2,-1,3.3,-2.7,1.1,2.2,-100]
output=[]
for i in inputs:
  if i>0:
    output.append(i)
  elif i<=0:
    output.append(0)
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [11]:
!pip install nnfs


Relu object

In [12]:
import nnfs
from nnfs.datasets import spiral_data
X,y=spiral_data(100,3)
class activation_relu:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)
class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights=.1*np.random.randn(n_inputs,n_neurons)#randn is just a gaussian distribution around 0, if values are more than  1 multiply by .1
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases
    
layer1=Layer_Dense(2,5)# this is a data for spiral graph therefore x and y cordinates will be the 2 features
activation1=activation_relu()
layer1.forward(X)
activation1.forward(layer1.output)
print(activation1.output)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504526e-04
  4.56845892e-05]
 [0.00000000e+00 5.93467943e-05 0.00000000e+00 2.03573189e-04
  6.10024276e-04]
 ...
 [1.13291515e-01 0.00000000e+00 0.00000000e+00 8.11079627e-02
  0.00000000e+00]
 [1.34588354e-01 0.00000000e+00 3.09493973e-02 5.66337522e-02
  0.00000000e+00]
 [1.07817915e-01 0.00000000e+00 0.00000000e+00 8.72561871e-02
  0.00000000e+00]]


Softmax function

specifically used for the output layer of classification type nn


In [13]:
import math
layer_output=[4.8,1.21,2.385]
E=math.e
output=[]
for op in layer_output:
  output.append(E**op)
print(output)


[121.51041751873483, 3.353484652549023, 10.859062664920513]


normalize-exponentiated values

combination of exponentiation and normalization makes up softmax

In [14]:
import math
layer_output=[4.8,1.21,2.385]
E=math.e
output=[]
for op in layer_output:
  output.append(E**op)
print(output)
norm_value=[]
norm_base=sum(output)
for values in output:
  norm_value.append(values / norm_base)
print(norm_value)
print(sum(norm_value))


[121.51041751873483, 3.353484652549023, 10.859062664920513]
[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


In [15]:
import math
import numpy as np

layer_output=[4.8,1.21,2.385]
E=math.e
output=np.exp(layer_output)
norm_values= output/np.sum(output)

print(norm_value)
print(sum(norm_value))

[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


Use softmax fn- for batch ip

note: axis parameter - none, default-take the sum of all values

0, column wise-> 1, row wise

note: keepdims=True, maintains the same dimension

In [16]:
import math
import numpy as np

input=[[4.8,1.21,2.385],[8.9,-1.81,0.2],[1.41,1.051,0.026]]
layer_output=np.exp(input)
sum=np.sum(layer_output, axis=1, keepdims=True)
norm_values= output/sum
print(norm_values)



[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [1.65695453e-02 4.57291786e-04 1.48077617e-03]
 [1.52215160e+01 4.20088428e-01 1.36030638e+00]]


use softmax activation class

In [17]:
import nnfs
from nnfs.datasets import spiral_data
X,y=spiral_data(100,4)
class activation_relu:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)
class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights=.1*np.random.randn(n_inputs,n_neurons)#randn is just a gaussian distribution around 0, if values are more than  1 multiply by .1
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases
class activation_softmax:
  def forward(self,inputs):
    exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
    probabilities=exp_values/np.sum(exp_values, axis=1, keepdims=True)
    self.output=probabilities
"""
define the layers
"""
dense1=Layer_Dense(2,3)
activation1=activation_relu()
dense2=Layer_Dense(3,3)#ip is the op of prev layer
activation2=activation_softmax()
"""
start propagation
"""
dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output)

[[0.33333333 0.33333333 0.33333333]
 [0.3333299  0.33333811 0.33333199]
 [0.33333667 0.33334203 0.3333213 ]
 ...
 [0.33333333 0.33333333 0.33333333]
 [0.33318544 0.33325489 0.33355967]
 [0.33333333 0.33333333 0.33333333]]
